function buildAgentsAttemptsQuery() {
  return `
SELECT 
    CONVERT(DATE, TIMESTAMP) AS [DATE], 
    DATEPART(HOUR, TIMESTAMP) AS [HOUR],
	CASE
		WHEN [AGENT NAME] LIKE 'ABC %' THEN 'ABC'
		WHEN [AGENT NAME] LIKE 'IMG %' THEN 'IMG'
		WHEN [AGENT NAME] LIKE 'VDM %' THEN 'VDM'
		WHEN [AGENT NAME] LIKE 'CZX %' THEN 'CZX'
		WHEN [AGENT NAME] = 'Naibi Jaimes' THEN 'IMG'
		WHEN [AGENT NAME] = 'Aleida Novelo' THEN 'ABC'
		WHEN [AGENT NAME] = 'Diego Paredes' THEN 'IMG'
		ELSE 'Otro'
	END AS 'Call Center',
    CASE
			WHEN [AGENT NAME] LIKE 'ABC %' THEN SUBSTRING([AGENT NAME], 5, LEN([AGENT NAME]))
			WHEN [AGENT NAME] LIKE 'IMG %' THEN SUBSTRING([AGENT NAME], 5, LEN([AGENT NAME]))
			WHEN [AGENT NAME] LIKE 'CZX %' THEN SUBSTRING([AGENT NAME], 5, LEN([AGENT NAME]))
			WHEN [AGENT NAME] LIKE 'VDM %' THEN SUBSTRING([AGENT NAME], 5, LEN([AGENT NAME]))
        ELSE [AGENT NAME]
		END AS [AGENT NAME],
    COUNT([AGENT NAME]) AS CallCount
FROM imgdb.INTAKE.Call_Records_five9
WHERE CONVERT(DATE, TIMESTAMP) = CONVERT(DATE, GETDATE())
AND (DISPOSITION IS NULL OR DISPOSITION NOT IN ('Inbound Queue Timeout Drop', 'Lead To Be Called', 'Agent Not Available','Inbound After Hours Drop',
'Outbound Pre-Routing Drop','Answering Machine Msg Played','Outbound Auto Dial'))
GROUP BY CONVERT(DATE, TIMESTAMP), DATEPART(HOUR, TIMESTAMP), [AGENT NAME]
`;
}

module.exports = {
  buildAgentsAttemptsQuery,
};

// WHERE CONVERT(DATE, TIMESTAMP) = CONVERT(DATE, GETDATE())

//WHERE CONVERT(DATE, TIMESTAMP) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))
